package drai.dev.gravelmon.games.pokemmo;

import drai.dev.gravelmon.pokemon.atlas.*;

public class Atlas extends drai.dev.gravelmon.games.registry.Game {
    public Atlas() {
        super("Atlas");
    }

    @Override
    public void registerPokemon() {
        pokemon.add(new Fawnlora());
        pokemon.add(new Botaneer());
        pokemon.add(new Forelk());
        pokemon.add(new Scurley());
        pokemon.add(new Burramble());
        pokemon.add(new Bramboom());
        pokemon.add(new Baneep());
        pokemon.add(new Bannawk());
        pokemon.add(new Phoenan());
        pokemon.add(new Instick());
        pokemon.add(new Inscepter());
        pokemon.add(new Chloradise());
        pokemon.add(new Nawdile());
        pokemon.add(new Aliblador());
        pokemon.add(new Razorvile());
        pokemon.add(new Scorchet());
        pokemon.add(new Torchet());
        pokemon.add(new Regalient());
        pokemon.add(new Vulkidna());
        pokemon.add(new Heatreme());
        pokemon.add(new Ekiama());
        pokemon.add(new Ruflame());
        pokemon.add(new Reparch());
        pokemon.add(new Slymander());
        pokemon.add(new Bunfin());
        pokemon.add(new Arsinge());
        pokemon.add(new Rupsen());
        pokemon.add(new Barkindle());
        pokemon.add(new Wolflaze());
        pokemon.add(new Wolverize());
        pokemon.add(new Finjoy());
        pokemon.add(new Finlock());
        pokemon.add(new Gandolph());
        pokemon.add(new Pumpel());
        pokemon.add(new Hydrank());
        pokemon.add(new Hydromedary());
        pokemon.add(new Liqueel());
        pokemon.add(new Electeel());
        pokemon.add(new Emporeel());
        pokemon.add(new Caimar());
        pokemon.add(new Torpeed());
        pokemon.add(new Damasoar());
        pokemon.add(new Watuber());
        pokemon.add(new Berswade());
        pokemon.add(new Chambrawl());

//        pokemon.add(new Akakira());
//        pokemon.add(new Akrovern());
//        pokemon.add(new Akute());
//        pokemon.add(new Albivore());
//        pokemon.add(new Algrain());
//        pokemon.add(new Alpalaine());
//        pokemon.add(new Ampin());
//        pokemon.add(new Anenemy());
//        pokemon.add(new Anglondor());
//        pokemon.add(new Aquarcher());
//        pokemon.add(new Aquaro());
//        pokemon.add(new Atolus());
//        pokemon.add(new Aurorelk());
//        pokemon.add(new Badgrow());
//        pokemon.add(new Bandicrook());
//        pokemon.add(new Baobloat());
//        pokemon.add(new Barilbil());
//        pokemon.add(new Barreef());
//        pokemon.add(new Barrose());
//        pokemon.add(new Bashbee());
//        pokemon.add(new Battenbae());
//        pokemon.add(new Bauldron());
//        pokemon.add(new Beaniscule());
//        pokemon.add(new Beanormous());
//        pokemon.add(new Birchard());
//        pokemon.add(new Birchee());
//        pokemon.add(new Birchop());
//        pokemon.add(new Bisommit());
//        pokemon.add(new Blizzund());
//        pokemon.add(new Bonafant());
//        pokemon.add(new Bosteroid());
//        pokemon.add(new Bouldalo());
//        pokemon.add(new Brambarb());
//        pokemon.add(new Brickler());
//        pokemon.add(new Bubbauld());
//        pokemon.add(new Buffhilla());
//        pokemon.add(new Bullirt());
//        pokemon.add(new Cachoe());
//        pokemon.add(new Caldona());
//        pokemon.add(new Campyre());
//        pokemon.add(new Caramelix());
//        pokemon.add(new Carnaceous());
//        pokemon.add(new Carnibble());
//        pokemon.add(new Carnosteus());
//        pokemon.add(new Carosella());
//        pokemon.add(new Charnosaur());
//        pokemon.add(new Cheecub());
//        pokemon.add(new Chronotoc());
//        pokemon.add(new Cindera());
//        pokemon.add(new Cloacover());
//        pokemon.add(new Cobworm());
//        pokemon.add(new Colosseel());
//        pokemon.add(new Compella());
//        pokemon.add(new Coralony());
//        pokemon.add(new Crebb());
//        pokemon.add(new Crescoon());
//        pokemon.add(new Criminook());
//        pokemon.add(new Crocodily());
//        pokemon.add(new Crustocean());
//        pokemon.add(new Dandylie());
//        pokemon.add(new Dandyseed());
//        pokemon.add(new Dartibi());
//        pokemon.add(new Devilicious());
//        pokemon.add(new Dialith());
//        pokemon.add(new Dilophang());
//        pokemon.add(new Dilophright());
//        pokemon.add(new Dirterrier());
//        pokemon.add(new Diskobolus());
//        pokemon.add(new Donguano());
//        pokemon.add(new Dustar());
//        pokemon.add(new Dwarpy());
//        pokemon.add(new Echidnum());
//        pokemon.add(new Edifierce());
//        pokemon.add(new Eelord());
//        pokemon.add(new Elastikrat());
//        pokemon.add(new Eldoredo());
//        pokemon.add(new Eletize());
//        pokemon.add(new Emperiegle());
//        pokemon.add(new Enkroach());
//        pokemon.add(new Eriegle());
//        pokemon.add(new Esterite());
//        pokemon.add(new Faram());
//        pokemon.add(new Fashewn());
//        pokemon.add(new Festiata());
//        pokemon.add(new Flamingant());
//        pokemon.add(new Flutterbi());
//        pokemon.add(new Foutune());
//        pokemon.add(new Fraxeel());
//        pokemon.add(new Freezef());
//        pokemon.add(new Froska());
//        pokemon.add(new Fumeseous());
//        pokemon.add(new Fumystic());
//        pokemon.add(new Galaguana());
//        pokemon.add(new Gammar());
//        pokemon.add(new Ganpaow());
//        pokemon.add(new Gassaster());
//        pokemon.add(new Gemmo());
//        pokemon.add(new Geomoss());
//        pokemon.add(new Ghouch());
//        pokemon.add(new Ghoulotine());
//        pokemon.add(new Gigadozer());
//        pokemon.add(new Glacyak());
//        pokemon.add(new Glacyte());
//        pokemon.add(new Glozard());
//        pokemon.add(new Goatee());
//        pokemon.add(new Grevetiery());
//        pokemon.add(new Guilloceive());
//        pokemon.add(new Haibril());
//        pokemon.add(new Harmorial());
//        pokemon.add(new Herokolus());
//        pokemon.add(new Hiberneedle());
//        pokemon.add(new Hoodloom());
//        pokemon.add(new Hoofrost());
//        pokemon.add(new Hoowhip());
//        pokemon.add(new Hoppereign());
//        pokemon.add(new Hoppiler());
//        pokemon.add(new Horrendove());
//        pokemon.add(new Hurdwall());
//        pokemon.add(new Icee());
//        pokemon.add(new Impac());
//        pokemon.add(new Impers());
//        pokemon.add(new Impie());
//        pokemon.add(new Imploda());
//        pokemon.add(new Imprism());
//        pokemon.add(new Impulso());
//        pokemon.add(new Jawligator());
//        pokemon.add(new Jayzul());
//        pokemon.add(new Jayzure());
//        pokemon.add(new Jollancer());
//        pokemon.add(new Junkid());
//        pokemon.add(new Juraseed());
//        pokemon.add(new Karaggon());
//        pokemon.add(new Kelprash());
//        pokemon.add(new Kelpush());
//        pokemon.add(new Kitture());
//        pokemon.add(new Korboral());
//        pokemon.add(new Kotukoatl());
//        pokemon.add(new Krillzaingel());
//        pokemon.add(new Lamber());
//        pokemon.add(new Lannelid());
//        pokemon.add(new Lemb());
//        pokemon.add(new Lepiterros());
//        pokemon.add(new Lickypop());
//        pokemon.add(new Lightwin());
//        pokemon.add(new Lizmoke());
//        pokemon.add(new Logrodile());
//        pokemon.add(new Luchaburro());
//        pokemon.add(new Luvenny());
//        pokemon.add(new Mafreozee());
//        pokemon.add(new Maidnite());
//        pokemon.add(new Mammolaya());
//        pokemon.add(new Mampth());
//        pokemon.add(new Manna());
//        pokemon.add(new Megatherice());
//        pokemon.add(new Meritrot());
//        pokemon.add(new Mesoth());
//        pokemon.add(new Mimish());
//        pokemon.add(new Moothnite());
//        pokemon.add(new Moppup());
//        pokemon.add(new Muscolin());
//        pokemon.add(new Musshield());
//        pokemon.add(new Nebulent());
//        pokemon.add(new Necrogeist());
//        pokemon.add(new Needella());
//        pokemon.add(new Needoon());
//        pokemon.add(new Needow());
//        pokemon.add(new Neonite());
//        pokemon.add(new Nuggle());
//        pokemon.add(new Nunette());
//        pokemon.add(new Nursee());
//        pokemon.add(new Nurturse());
//        pokemon.add(new Nuttone());
//        pokemon.add(new Nyglare());
//        pokemon.add(new Nyglow());
//        pokemon.add(new Oburious());
//        pokemon.add(new Orbranch());
//        pokemon.add(new Orotolas());
//        pokemon.add(new Osstrike());
//        pokemon.add(new Otamot());
//        pokemon.add(new Pangai());
//        pokemon.add(new Paow());
//        pokemon.add(new Penguinsula());
//        pokemon.add(new Petat());
//        pokemon.add(new Petrifern());
//        pokemon.add(new Phanfrica());
//        pokemon.add(new Phanta());
//        pokemon.add(new Phantomail());
//        pokemon.add(new Phantrait());
//        pokemon.add(new Pichip());
//        pokemon.add(new Piragmid());
//        pokemon.add(new Pitchzall());
//        pokemon.add(new Polynett());
//        pokemon.add(new Polypus());
//        pokemon.add(new Polyzap());
//        pokemon.add(new Prickub());
//        pokemon.add(new Princeo());
//        pokemon.add(new Quetzap());
//        pokemon.add(new Radiaze());
//        pokemon.add(new Radizorb());
//        pokemon.add(new Ragtoc());
//        pokemon.add(new Rapterra());
//        pokemon.add(new Rattoi());
//        pokemon.add(new Refhuge());
//        pokemon.add(new Reileo());
//        pokemon.add(new Reparine());
//        pokemon.add(new Revolpod());
//        pokemon.add(new Roachem());
//        pokemon.add(new Roostegg());
//        pokemon.add(new Sandan());
//        pokemon.add(new Sandemonium());
//        pokemon.add(new Sandevil());
//        pokemon.add(new Sandshar());
//        pokemon.add(new Sandtome());
//        pokemon.add(new Sauntler());
//        pokemon.add(new Scubella());
//        pokemon.add(new Secheel());
//        pokemon.add(new Seedent());
//        pokemon.add(new Serrarbo());
//        pokemon.add(new Shalazhimm());
//        pokemon.add(new Shampooch());
//        pokemon.add(new Sharkastle());
//        pokemon.add(new Sharquake());
//        pokemon.add(new Sheruption());
//        pokemon.add(new Shifuu());
//        pokemon.add(new Shimm());
//        pokemon.add(new Shoaly());
//        pokemon.add(new Shockatoo());
//        pokemon.add(new Silkch());
//        pokemon.add(new Silxie());
//        pokemon.add(new Sisanne());
//        pokemon.add(new Skibis());
//        pokemon.add(new Skweakrat());
//        pokemon.add(new Slithair());
//        pokemon.add(new Snowoof());
//        pokemon.add(new Solmec());
//        pokemon.add(new Spartzle());
//        pokemon.add(new Speeda());
//        pokemon.add(new Spireye());
//        pokemon.add(new Squabling());
//        pokemon.add(new Squirest());
//        pokemon.add(new Stalagang());
//        pokemon.add(new Stalagrunt());
//        pokemon.add(new Stalliot());
//        pokemon.add(new Stellarva());
//        pokemon.add(new Stelnova());
//        pokemon.add(new Strikezall());
//        pokemon.add(new Stuckarp());
//        pokemon.add(new Stuckry());
//        pokemon.add(new Suavenny());
//        pokemon.add(new Submurchin());
//        pokemon.add(new Suburvian());
//        pokemon.add(new Surchin());
//        pokemon.add(new Tamarawk());
//        pokemon.add(new Tanchor());
//        pokemon.add(new Tankton());
//        pokemon.add(new Tankyard());
//        pokemon.add(new Terbipan());
//        pokemon.add(new Thorlock());
//        pokemon.add(new Thundret());
//        pokemon.add(new Tinguano());
//        pokemon.add(new Titanodon());
//        pokemon.add(new Tomabi());
//        pokemon.add(new Torrojo());
//        pokemon.add(new Toxitube());
//        pokemon.add(new Treezen());
//        pokemon.add(new Trillowee());
//        pokemon.add(new Tulifun());
//        pokemon.add(new Turtelisk());
//        pokemon.add(new Twoolepin());
//        pokemon.add(new Vanitom());
//        pokemon.add(new Vegelamb());
//        pokemon.add(new Velosoil());
//        pokemon.add(new Vermini());
//        pokemon.add(new Vermpent());
//        pokemon.add(new Vimana());
//        pokemon.add(new Vimanzia());
//        pokemon.add(new Visclaw());
//        pokemon.add(new Volpaca());
//        pokemon.add(new Whelter());
//        pokemon.add(new Wicktrive());
//        pokemon.add(new Wickvine());
//        pokemon.add(new Wildyre());
//        pokemon.add(new Wilspri());
//        pokemon.add(new Wisdaum());
//        pokemon.add(new Wisper());
//        pokemon.add(new Wispette());
//        pokemon.add(new Withereen());
//        pokemon.add(new Wombabe());
//        pokemon.add(new Woolam());
//        pokemon.add(new Wreclaw());
//        pokemon.add(new Yanpaow());
//        pokemon.add(new Yokeye());
//        pokemon.add(new Yolken());
//        pokemon.add(new Zaptang());
//        pokemon.add(new Zentipreeze());
//        pokemon.add(new Zhimm());
    }

}
