package drai.dev.gravelmon.games.pokemmo;

import drai.dev.gravelmon.pokemon.atlas.*;
import drai.dev.gravelmon.pokemon.atlas.Akrovern;
import drai.dev.gravelmon.pokemon.atlas.Albivore;
import drai.dev.gravelmon.pokemon.atlas.Carosella;
import drai.dev.gravelmon.pokemon.atlas.Eletize;
import drai.dev.gravelmon.pokemon.atlas.Emperiegle;
import drai.dev.gravelmon.pokemon.atlas.Eriegle;
import drai.dev.gravelmon.pokemon.atlas.Glozard;
import drai.dev.gravelmon.pokemon.atlas.Karaggon;
import drai.dev.gravelmon.pokemon.atlas.Luvenny;
import drai.dev.gravelmon.pokemon.atlas.Meritrot;
import drai.dev.gravelmon.pokemon.atlas.Nursee;
import drai.dev.gravelmon.pokemon.atlas.Nurturse;
import drai.dev.gravelmon.pokemon.atlas.Radiaze;
import drai.dev.gravelmon.pokemon.atlas.Radizorb;
import drai.dev.gravelmon.pokemon.atlas.Spartzle;
import drai.dev.gravelmon.pokemon.atlas.Stalliot;
import drai.dev.gravelmon.pokemon.atlas.Suavenny;
import drai.dev.gravelmon.pokemon.atlas.Trillowee;
import drai.dev.gravelmon.pokemon.atlas.Turtelisk;
import drai.dev.gravelmon.pokemon.atlas.Wilspri;
import drai.dev.gravelmon.pokemon.orohnhavai.*;

public class OrohnHavai extends drai.dev.gravelmon.games.registry.Game {
    public OrohnHavai() {
        super("Orohn-Havai");
    }

    @Override
    public void registerPokemon() {
//        pokemon.add(new Abyssoul());
//        pokemon.add(new Aidelf());
//        pokemon.add(new Akrovern());
//        pokemon.add(new Albivore());
//        pokemon.add(new Alomomola());
//        pokemon.add(new Alpheon());
//        pokemon.add(new Antzooka());
//        pokemon.add(new Arblizen());
//        pokemon.add(new Armodieval());
//        pokemon.add(new Arrocknid());
//        pokemon.add(new Axeleraze());
//        pokemon.add(new Barbenin());
//        pokemon.add(new Bonzire());
//        pokemon.add(new Bonzumi());
//        pokemon.add(new Burnuki());
//        pokemon.add(new Camofirma());
//        pokemon.add(new Camohut());
//        pokemon.add(new Caraprisma());
//        pokemon.add(new Carosella());
//        pokemon.add(new Chainect());
//        pokemon.add(new Chainector());
//        var chemecko = new Chemecko();
//        pokemon.add(chemecko);
////        pokemon.add(new AvorianChemecko(chemecko.getPokedexNumber()));
//        pokemon.add(new Chenileaf());
//        pokemon.add(new Chillimp());
//        pokemon.add(new Chiroo());
//        pokemon.add(new Clastroid());
//        pokemon.add(new Clawconut());
//        pokemon.add(new Clawgigus());
//        pokemon.add(new Colistroid());
//        pokemon.add(new Cosminx());
//        pokemon.add(new Cottoon());
//        pokemon.add(new Cryosect());
//        pokemon.add(new Darcastro());
//        pokemon.add(new Devostoric());
//        pokemon.add(new Dorentu());
//        pokemon.add(new Drazephir());
//        pokemon.add(new Ekopi());
//        pokemon.add(new Ekoraft());
//        pokemon.add(new Elecko());
//        pokemon.add(new Eletize());
//        pokemon.add(new Elfini());
//        pokemon.add(new Emperiegle());
//        pokemon.add(new Empressea());
//        pokemon.add(new Eriegle());
//        pokemon.add(new Eskiflurr());
//        pokemon.add(new Eveon());
//        pokemon.add(new Exoroknid());
//        pokemon.add(new Expertri());
//        pokemon.add(new Ferobite());
//        pokemon.add(new Finray());
//        pokemon.add(new Flabb());
//        pokemon.add(new Flaero());
//        pokemon.add(new Flambagant());
//        pokemon.add(new Fleuroma());
//        pokemon.add(new Fortibal());
//        pokemon.add(new Foxsye());
//        pokemon.add(new Fribitad());
//        pokemon.add(new Frossit());
//        pokemon.add(new Fyglow());
//        pokemon.add(new Galixoid());
//        pokemon.add(new Garglizer());
//        pokemon.add(new Gargobble());
//        pokemon.add(new Generion());
//        pokemon.add(new Geoglyphic());
//        pokemon.add(new Gleamur());
//        pokemon.add(new Glimpid());
//        pokemon.add(new Glozard());
//        pokemon.add(new Glumence());
//        pokemon.add(new Glumexin());
//        pokemon.add(new Goosea());
//        pokemon.add(new Granderosa());
//        pokemon.add(new Grandorent());
//        pokemon.add(new Hematick());
//        pokemon.add(new Imbumi());
//        pokemon.add(new Impferno());
//        pokemon.add(new Indureion());
//        pokemon.add(new Infiluv());
//        pokemon.add(new Intelix());
//        pokemon.add(new Kahukele());
//        pokemon.add(new Karaggon());
//        pokemon.add(new Kelpony());
//        pokemon.add(new Kloakroach());
//        pokemon.add(new Kombantis());
//        pokemon.add(new Konchore());
//        pokemon.add(new Kragodon());
//        pokemon.add(new Kraklam());
//        pokemon.add(new Krakshen());
//        pokemon.add(new Kroach());
//        pokemon.add(new Lemomi());
//        pokemon.add(new Lilabaa());
//        pokemon.add(new Lulabaa());
//        pokemon.add(new Luvenny());
//        pokemon.add(new Malakele());
//        pokemon.add(new Maritide());
//        pokemon.add(new Meritrot());
//        pokemon.add(new Molozard());
//        pokemon.add(new Mousense());
//        pokemon.add(new Nawdile());
//        pokemon.add(new Nectavian());
//        pokemon.add(new Neinei());
//        pokemon.add(new Neptide());
//        pokemon.add(new Nervreck());
//        pokemon.add(new Netherval());
//        pokemon.add(new Noxareo());
//        pokemon.add(new Nursee());
//        pokemon.add(new Nurturse());
//        pokemon.add(new Obideion());
//        pokemon.add(new Ogoprowl());
//        pokemon.add(new Oreglyph());
//        pokemon.add(new Pebblent());
//        pokemon.add(new Petirex());
//        pokemon.add(new Petumi());
//        pokemon.add(new Phrilter());
//        pokemon.add(new Pinxie());
//        pokemon.add(new Pipsicle());
//        pokemon.add(new Pitopyre());
        pokemon.add(new Pixiechu());
//        pokemon.add(new Polighoul());
//        pokemon.add(new Purswayer());
//        pokemon.add(new Pyrovern());
//        pokemon.add(new Quadrossal());
//        pokemon.add(new Radiaze());
//        pokemon.add(new Radizorb());
//        pokemon.add(new Reefallion());
//        pokemon.add(new Reefermal());
//        pokemon.add(new Ribivine());
//        pokemon.add(new Rivulcred());
//        pokemon.add(new Rocroset());
//        pokemon.add(new Ruffski());
//        pokemon.add(new Scoprikon());
//        pokemon.add(new Sedavlin());
//        pokemon.add(new Sensarat());
//        pokemon.add(new Sephysar());
//        pokemon.add(new Sharfin());
//        pokemon.add(new Shelmissy());
//        pokemon.add(new Shiveram());
//        pokemon.add(new Siberizen());
//        pokemon.add(new Slickitty());
//        pokemon.add(new Slotherror());
//        pokemon.add(new Snowool());
//        pokemon.add(new Spartzle());
//        pokemon.add(new Stalliot());
//        pokemon.add(new Stegovore());
//        pokemon.add(new Stegrump());
//        pokemon.add(new Suavenny());
//        pokemon.add(new Tadapt());
//        pokemon.add(new Tasticky());
//        pokemon.add(new Tekichu());
//        pokemon.add(new Therasloth());
//        pokemon.add(new Thistling());
//        pokemon.add(new Thornment());
//        pokemon.add(new Thrashark());
//        pokemon.add(new Timiby());
//        pokemon.add(new Timingo());
//        pokemon.add(new Trairoo());
//        pokemon.add(new Trillowee());
//        pokemon.add(new Troopant());
//        pokemon.add(new Tundrill());
//        pokemon.add(new Turtelisk());
//        pokemon.add(new Twirpant());
//        pokemon.add(new Valecred());
//        pokemon.add(new Veilvid());
//        pokemon.add(new Veroxifye());
//        pokemon.add(new Vexigon());
//        pokemon.add(new Voidevour());
//        pokemon.add(new Vortexol());
//        pokemon.add(new Vorvosip());
//        pokemon.add(new Warblu());
//        pokemon.add(new Territore());
//        pokemon.add(new Warshrike());
//        pokemon.add(new Brambarb());
//        pokemon.add(new Wickvine());
//        pokemon.add(new Wicktrive());
//        pokemon.add(new Wilspri());
//        pokemon.add(new Winklit());
//        pokemon.add(new Withettle());
//        pokemon.add(new Wooble());
//        pokemon.add(new Wreckasaur());
//        pokemon.add(new Wreckore());
//        pokemon.add(new Zapcoon());
//        pokemon.add(new Zapillar());
//        pokemon.add(new Zaptenna());
//        pokemon.add(new Zedakazm());
    }

}
