//package com.gravelmon.common.gravelmon.pokemon.official.one;
//
//import com.gravelmon.common.gravelmon.pokemon.*;
//import com.gravelmon.common.gravelmon.pokemon.attributes.*;
//import com.gravelmon.common.gravelmon.pokemon.attributes.conditions.*;
//
//import java.util.*;
//
//public class Nidorina extends Pokemon {
//    public Nidorina(int dexNo) {
//        super(dexNo,"Nidorina",
//                Type.POISON,
//                new Stats(70, 62, 67, 55, 55, 56),
//                List.of(Ability.POISON_POINT, Ability.RIVALRY), Ability.HUSTLE,
//                4, 60,
//                new Stats(2,0,0,0,0,0), 190,
//                0.5,
//                128, ExperienceGroup.MEDIUM_SLOW,
//                70,
//                20, List.of(EggGroup.UNDISCOVERED),
//                List.of(""),
//                List.of(new EvolutionEntry("nidoqueen", EvolutionType.ITEM_INTERACT, false, List.of(new MoveLearnSetEntry(Move.SUPERPOWER, "")),
//                                List.of(),List.of(),"cobblemon:moon_stone"),
//                        new EvolutionEntry("nidorook", EvolutionType.ITEM_INTERACT, false, List.of(),
//                                List.of(),List.of(),"minecraft:quartz")),
//                List.of(
//                        new MoveLearnSetEntry(Move.GROWL,1),
//                        new MoveLearnSetEntry(Move.SCRATCH,1),
//                        new MoveLearnSetEntry(Move.TAIL_WHIP,8),
//                        new MoveLearnSetEntry(Move.DOUBLE_KICK,12),
//                        new MoveLearnSetEntry(Move.POISON_STING,18),
//                        new MoveLearnSetEntry(Move.BITE,22),
//                        new MoveLearnSetEntry(Move.HELPING_HAND,26),
//                        new MoveLearnSetEntry(Move.FURY_SWIPES,34),
//                        new MoveLearnSetEntry(Move.TOXIC_SPIKES,35),
//                        new MoveLearnSetEntry(Move.FLATTER,43),
//                        new MoveLearnSetEntry(Move.CAPTIVATE,50),
//                        new MoveLearnSetEntry(Move.TOXIC,50),
//                        new MoveLearnSetEntry(Move.CRUNCH,53),
//                        new MoveLearnSetEntry(Move.POISON_FANG,58),
//                        new MoveLearnSetEntry(Move.EARTH_POWER,71),
//                        new MoveLearnSetEntry(Move.AERIAL_ACE,"tm"),
//                        new MoveLearnSetEntry(Move.ATTRACT,"tm"),
//                        new MoveLearnSetEntry(Move.BEAT_UP,"tm"),
//                        new MoveLearnSetEntry(Move.BLIZZARD,"tm"),
//                        new MoveLearnSetEntry(Move.BODY_SLAM,"tm"),
//                        new MoveLearnSetEntry(Move.CAPTIVATE,"tm"),
//                        new MoveLearnSetEntry(Move.CHARM,"tm"),
//                        new MoveLearnSetEntry(Move.CONFIDE,"tm"),
//                        new MoveLearnSetEntry(Move.CRUNCH,"tm"),
//                        new MoveLearnSetEntry(Move.CUT,"tm"),
//                        new MoveLearnSetEntry(Move.DIG,"tm"),
//                        new MoveLearnSetEntry(Move.DOUBLE_TEAM,"tm"),
//                        new MoveLearnSetEntry(Move.EARTH_POWER,"tm"),
//                        new MoveLearnSetEntry(Move.ECHOED_VOICE,"tm"),
//                        new MoveLearnSetEntry(Move.ENDURE,"tm"),
//                        new MoveLearnSetEntry(Move.FACADE,"tm"),
//                        new MoveLearnSetEntry(Move.FOCUS_ENERGY,"tm"),
//                        new MoveLearnSetEntry(Move.FRUSTRATION,"tm"),
//                        new MoveLearnSetEntry(Move.HELPING_HAND,"tm"),
//                        new MoveLearnSetEntry(Move.HIDDEN_POWER,"tm"),
//                        new MoveLearnSetEntry(Move.HONE_CLAWS,"tm"),
//                        new MoveLearnSetEntry(Move.ICE_BEAM,"tm"),
//                        new MoveLearnSetEntry(Move.IRON_TAIL,"tm"),
//                        new MoveLearnSetEntry(Move.NATURAL_GIFT,"tm"),
//                        new MoveLearnSetEntry(Move.POISON_JAB,"tm"),
//                        new MoveLearnSetEntry(Move.PROTECT,"tm"),
//                        new MoveLearnSetEntry(Move.RAIN_DANCE,"tm"),
//                        new MoveLearnSetEntry(Move.REST,"tm"),
//                        new MoveLearnSetEntry(Move.RETURN,"tm"),
//                        new MoveLearnSetEntry(Move.ROCK_SMASH,"tm"),
//                        new MoveLearnSetEntry(Move.ROUND,"tm"),
//                        new MoveLearnSetEntry(Move.SECRET_POWER,"tm"),
//                        new MoveLearnSetEntry(Move.SHADOW_CLAW,"tm"),
//                        new MoveLearnSetEntry(Move.SHOCK_WAVE,"tm"),
//                        new MoveLearnSetEntry(Move.SLEEP_TALK,"tm"),
//                        new MoveLearnSetEntry(Move.SLUDGE_BOMB,"tm"),
//                        new MoveLearnSetEntry(Move.SNORE,"tm"),
//                        new MoveLearnSetEntry(Move.STOMPING_TANTRUM,"tm"),
//                        new MoveLearnSetEntry(Move.STRENGTH,"tm"),
//                        new MoveLearnSetEntry(Move.SUBSTITUTE,"tm"),
//                        new MoveLearnSetEntry(Move.SUNNY_DAY,"tm"),
//                        new MoveLearnSetEntry(Move.SWAGGER,"tm"),
//                        new MoveLearnSetEntry(Move.THIEF,"tm"),
//                        new MoveLearnSetEntry(Move.THUNDER,"tm"),
//                        new MoveLearnSetEntry(Move.THUNDERBOLT,"tm"),
//                        new MoveLearnSetEntry(Move.TOXIC,"tm"),
//                        new MoveLearnSetEntry(Move.TOXIC_SPIKES,"tm"),
//                        new MoveLearnSetEntry(Move.VENOM_DRENCH,"tm"),
//                        new MoveLearnSetEntry(Move.VENOSHOCK,"tm"),
//                        new MoveLearnSetEntry(Move.WATER_PULSE,"tm"),
//                        new MoveLearnSetEntry(Move.ATTRACT,"tutor"),
//                        new MoveLearnSetEntry(Move.BIDE,"tutor"),
//                        new MoveLearnSetEntry(Move.BITE,"tutor"),
//                        new MoveLearnSetEntry(Move.BLIZZARD,"tutor"),
//                        new MoveLearnSetEntry(Move.BODY_SLAM,"tutor"),
//                        new MoveLearnSetEntry(Move.BUBBLE_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.COUNTER,"tutor"),
//                        new MoveLearnSetEntry(Move.CRUNCH,"tutor"),
//                        new MoveLearnSetEntry(Move.CURSE,"tutor"),
//                        new MoveLearnSetEntry(Move.DEFENSE_CURL,"tutor"),
//                        new MoveLearnSetEntry(Move.DETECT,"tutor"),
//                        new MoveLearnSetEntry(Move.DIG,"tutor"),
//                        new MoveLearnSetEntry(Move.DOUBLEEDGE,"tutor"),
//                        new MoveLearnSetEntry(Move.DOUBLE_KICK,"tutor"),
//                        new MoveLearnSetEntry(Move.DOUBLE_TEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.ENDURE,"tutor"),
//                        new MoveLearnSetEntry(Move.FACADE,"tutor"),
//                        new MoveLearnSetEntry(Move.FRUSTRATION,"tutor"),
//                        new MoveLearnSetEntry(Move.FURY_SWIPES,"tutor"),
//                        new MoveLearnSetEntry(Move.GROWL,"tutor"),
//                        new MoveLearnSetEntry(Move.HEADBUTT,"tutor"),
//                        new MoveLearnSetEntry(Move.HELPING_HAND,"tutor"),
//                        new MoveLearnSetEntry(Move.HIDDEN_POWER,"tutor"),
//                        new MoveLearnSetEntry(Move.HORN_DRILL,"tutor"),
//                        new MoveLearnSetEntry(Move.ICE_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.IRON_TAIL,"tutor"),
//                        new MoveLearnSetEntry(Move.MIMIC,"tutor"),
//                        new MoveLearnSetEntry(Move.MUDSLAP,"tutor"),
//                        new MoveLearnSetEntry(Move.POISON_JAB,"tutor"),
//                        new MoveLearnSetEntry(Move.POISON_STING,"tutor"),
//                        new MoveLearnSetEntry(Move.PROTECT,"tutor"),
//                        new MoveLearnSetEntry(Move.RAGE,"tutor"),
//                        new MoveLearnSetEntry(Move.RAIN_DANCE,"tutor"),
//                        new MoveLearnSetEntry(Move.REFLECT,"tutor"),
//                        new MoveLearnSetEntry(Move.REST,"tutor"),
//                        new MoveLearnSetEntry(Move.RETURN,"tutor"),
//                        new MoveLearnSetEntry(Move.ROCK_SMASH,"tutor"),
//                        new MoveLearnSetEntry(Move.SCRATCH,"tutor"),
//                        new MoveLearnSetEntry(Move.SHOCK_WAVE,"tutor"),
//                        new MoveLearnSetEntry(Move.SKULL_BASH,"tutor"),
//                        new MoveLearnSetEntry(Move.SLEEP_TALK,"tutor"),
//                        new MoveLearnSetEntry(Move.SLUDGE_BOMB,"tutor"),
//                        new MoveLearnSetEntry(Move.SNORE,"tutor"),
//                        new MoveLearnSetEntry(Move.STOMPING_TANTRUM,"tutor"),
//                        new MoveLearnSetEntry(Move.STRENGTH,"tutor"),
//                        new MoveLearnSetEntry(Move.SUBSTITUTE,"tutor"),
//                        new MoveLearnSetEntry(Move.SUNNY_DAY,"tutor"),
//                        new MoveLearnSetEntry(Move.SUPER_FANG,"tutor"),
//                        new MoveLearnSetEntry(Move.SWAGGER,"tutor"),
//                        new MoveLearnSetEntry(Move.TACKLE,"tutor"),
//                        new MoveLearnSetEntry(Move.TAIL_WHIP,"tutor"),
//                        new MoveLearnSetEntry(Move.TAKE_DOWN,"tutor"),
//                        new MoveLearnSetEntry(Move.THIEF,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDER,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDERBOLT,"tutor"),
//                        new MoveLearnSetEntry(Move.TOXIC,"tutor"),
//                        new MoveLearnSetEntry(Move.WATER_GUN,"tutor"),
//                        new MoveLearnSetEntry(Move.WATER_PULSE,"tutor"),
//                        new MoveLearnSetEntry(Move.HEADBUTT,"tutor"),
//                        new MoveLearnSetEntry(Move.HEART_STAMP,"tutor"),
//                        new MoveLearnSetEntry(Move.HELPING_HAND,"tutor"),
//                        new MoveLearnSetEntry(Move.HIDDEN_POWER,"tutor"),
//                        new MoveLearnSetEntry(Move.HOLD_HANDS,"tutor"),
//                        new MoveLearnSetEntry(Move.IRON_TAIL,"tutor"),
//                        new MoveLearnSetEntry(Move.KNOCK_OFF,"tutor"),
//                        new MoveLearnSetEntry(Move.LASER_FOCUS,"tutor"),
//                        new MoveLearnSetEntry(Move.LAST_RESORT,"tutor"),
//                        new MoveLearnSetEntry(Move.LIGHT_SCREEN,"tutor"),
//                        new MoveLearnSetEntry(Move.MAGNET_RISE,"tutor"),
//                        new MoveLearnSetEntry(Move.MEGA_KICK,"tutor"),
//                        new MoveLearnSetEntry(Move.MEGA_PUNCH,"tutor"),
//                        new MoveLearnSetEntry(Move.MIMIC,"tutor"),
//                        new MoveLearnSetEntry(Move.MUDSLAP,"tutor"),
//                        new MoveLearnSetEntry(Move.NUZZLE,"tutor"),
//                        new MoveLearnSetEntry(Move.PAY_DAY,"tutor"),
//                        new MoveLearnSetEntry(Move.PLAY_NICE,"tutor"),
//                        new MoveLearnSetEntry(Move.PRESENT,"tutor"),
//                        new MoveLearnSetEntry(Move.PROTECT,"tutor"),
//                        new MoveLearnSetEntry(Move.QUICK_ATTACK,"tutor"),
//                        new MoveLearnSetEntry(Move.RAGE,"tutor"),
//                        new MoveLearnSetEntry(Move.RAIN_DANCE,"tutor"),
//                        new MoveLearnSetEntry(Move.REFLECT,"tutor"),
//                        new MoveLearnSetEntry(Move.REFRESH,"tutor"),
//                        new MoveLearnSetEntry(Move.REST,"tutor"),
//                        new MoveLearnSetEntry(Move.RETURN,"tutor"),
//                        new MoveLearnSetEntry(Move.RISING_VOLTAGE,"tutor"),
//                        new MoveLearnSetEntry(Move.ROLLOUT,"tutor"),
//                        new MoveLearnSetEntry(Move.SEISMIC_TOSS,"tutor"),
//                        new MoveLearnSetEntry(Move.SHOCK_WAVE,"tutor"),
//                        new MoveLearnSetEntry(Move.SIGNAL_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.SING,"tutor"),
//                        new MoveLearnSetEntry(Move.SKULL_BASH,"tutor"),
//                        new MoveLearnSetEntry(Move.SLAM,"tutor"),
//                        new MoveLearnSetEntry(Move.SLEEP_TALK,"tutor"),
//                        new MoveLearnSetEntry(Move.SNORE,"tutor"),
//                        new MoveLearnSetEntry(Move.STRENGTH,"tutor"),
//                        new MoveLearnSetEntry(Move.SUBMISSION,"tutor"),
//                        new MoveLearnSetEntry(Move.SUBSTITUTE,"tutor"),
//                        new MoveLearnSetEntry(Move.SURF,"tutor"),
//                        new MoveLearnSetEntry(Move.SWAGGER,"tutor"),
//                        new MoveLearnSetEntry(Move.SWEET_KISS,"tutor"),
//                        new MoveLearnSetEntry(Move.SWEET_SCENT,"tutor"),
//                        new MoveLearnSetEntry(Move.SWIFT,"tutor"),
//                        new MoveLearnSetEntry(Move.TAIL_WHIP,"tutor"),
//                        new MoveLearnSetEntry(Move.TAKE_DOWN,"tutor"),
//                        new MoveLearnSetEntry(Move.TEETER_DANCE,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDER,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDERBOLT,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDER_PUNCH,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDER_SHOCK,"tutor"),
//                        new MoveLearnSetEntry(Move.THUNDER_WAVE,"tutor"),
//                        new MoveLearnSetEntry(Move.TOXIC,"tutor"),
//                        new MoveLearnSetEntry(Move.VOLT_SWITCH,"tutor"),
//                        new MoveLearnSetEntry(Move.VOLT_TACKLE,"tutor"),
//                        new MoveLearnSetEntry(Move.WISH,"tutor"),
//                        new MoveLearnSetEntry(Move.YAWN,"tutor"),
//                        new MoveLearnSetEntry(Move.ZAP_CANNON,"tutor")
//                        ),
//                List.of(Label.GEN1),
//                1, List.of(
//                        new ItemDrop("cobblemon:poison_barb", 5, 1,1)
//                ),
//                SpawnContext.GROUNDED, SpawnPool.UNCOMMON, 16, 36, 0.9, List.of(
//                        new BiomeSpawnCondition(List.of(Biome.IS_SAVANNA)),
//                        new SpawnCondition(SpawnConditionType.TIMERANGE, "day"),
//                        new SpawnCondition(SpawnConditionType.CANSEESKY,"true")
//                ), List.of(new BiomeSpawnCondition(List.of(Biome.IS_SPOOKY))),
//                List.of(SpawnPreset.NATURAL),
//                0.9, 0.3,
//                List.of());
//        this.setIsNew(false);
//        this.setHitbox(1,0.8);
//        this.setPortraitXYZ(0,1.8,0);
//    }
//}
