//package com.gravelmon.common.gravelmon.pokemon.official.one;
//
//import com.gravelmon.common.gravelmon.pokemon.*;
//import com.gravelmon.common.gravelmon.pokemon.attributes.*;
//import com.gravelmon.common.gravelmon.pokemon.attributes.conditions.*;
//
//import java.util.*;
//
//public class Shellder extends Pokemon {
//    public Shellder(int dexNo) {
//        super(dexNo,"Shellder",
//                Type.WATER,
//                new Stats(30, 65, 100, 45, 25, 40),
//                List.of(Ability.SHELL_ARMOR, Ability.SKILL_LINK), Ability.OVERCOAT,
//                3, 40,
//                new Stats(0,0,1,0,0,0), 190,
//                0.5,
//                61, ExperienceGroup.SLOW,
//                70,
//                20, List.of(EggGroup.WATER_3),
//                List.of(""),
//                //TODO replace iron ingot with slowpoke tail when implemented
//                List.of(new EvolutionEntry("cloyster", EvolutionType.ITEM_INTERACT, false, List.of(new MoveLearnSetEntry(Move.ICICLE_SPEAR,"")),
//                        List.of(),List.of(),"cobblemon:water_stone"),
//                        new EvolutionEntry("ehgoshellder", EvolutionType.ITEM_INTERACT, false, List.of(),
//                                List.of(),List.of(),"minecraft:iron_ingot")),
//                List.of(
//                        new MoveLearnSetEntry(Move.TACKLE,1),
//                        new MoveLearnSetEntry(Move.WATER_GUN,1),
//                        new MoveLearnSetEntry(Move.WITHDRAW,1),
//                        new MoveLearnSetEntry(Move.ICICLE_SPEAR,8),
//                        new MoveLearnSetEntry(Move.SUPERSONIC,9),
//                        new MoveLearnSetEntry(Move.AURORA_BEAM,17),
//                        new MoveLearnSetEntry(Move.PROTECT,25),
//                        new MoveLearnSetEntry(Move.ICE_SHARD,28),
//                        new MoveLearnSetEntry(Move.RAZOR_SHELL,32),
//                        new MoveLearnSetEntry(Move.LEER,33),
//                        new MoveLearnSetEntry(Move.WHIRLPOOL,37),
//                        new MoveLearnSetEntry(Move.IRON_DEFENSE,40),
//                        new MoveLearnSetEntry(Move.CLAMP,41),
//                        new MoveLearnSetEntry(Move.BRINE,44),
//                        new MoveLearnSetEntry(Move.ICE_BEAM,49),
//                        new MoveLearnSetEntry(Move.SHELL_SMASH,56),
//                        new MoveLearnSetEntry(Move.HYDRO_PUMP,61),
//                        new MoveLearnSetEntry(Move.AQUA_RING,"egg"),
//                        new MoveLearnSetEntry(Move.AVALANCHE,"egg"),
//                        new MoveLearnSetEntry(Move.BARRIER,"egg"),
//                        new MoveLearnSetEntry(Move.BUBBLE_BEAM,"egg"),
//                        new MoveLearnSetEntry(Move.ICICLE_SPEAR,"egg"),
//                        new MoveLearnSetEntry(Move.LIFE_DEW,"egg"),
//                        new MoveLearnSetEntry(Move.MUD_SHOT,"egg"),
//                        new MoveLearnSetEntry(Move.RAPID_SPIN,"egg"),
//                        new MoveLearnSetEntry(Move.ROCK_BLAST,"egg"),
//                        new MoveLearnSetEntry(Move.SCREECH,"egg"),
//                        new MoveLearnSetEntry(Move.TAKE_DOWN,"egg"),
//                        new MoveLearnSetEntry(Move.TWINEEDLE,"egg"),
//                        new MoveLearnSetEntry(Move.WATER_PULSE,"egg"),
//                        new MoveLearnSetEntry(Move.ATTRACT,"tm"),
//                        new MoveLearnSetEntry(Move.AVALANCHE,"tm"),
//                        new MoveLearnSetEntry(Move.BLIZZARD,"tm"),
//                        new MoveLearnSetEntry(Move.BRINE,"tm"),
//                        new MoveLearnSetEntry(Move.CAPTIVATE,"tm"),
//                        new MoveLearnSetEntry(Move.CHILLING_WATER,"tm"),
//                        new MoveLearnSetEntry(Move.CONFIDE,"tm"),
//                        new MoveLearnSetEntry(Move.DIVE,"tm"),
//                        new MoveLearnSetEntry(Move.DOUBLE_TEAM,"tm"),
//                        new MoveLearnSetEntry(Move.ENDURE,"tm"),
//                        new MoveLearnSetEntry(Move.EXPLOSION,"tm"),
//                        new MoveLearnSetEntry(Move.FACADE,"tm"),
//                        new MoveLearnSetEntry(Move.FRUSTRATION,"tm"),
//                        new MoveLearnSetEntry(Move.HAIL,"tm"),
//                        new MoveLearnSetEntry(Move.HELPING_HAND,"tm"),
//                        new MoveLearnSetEntry(Move.HIDDEN_POWER,"tm"),
//                        new MoveLearnSetEntry(Move.HYDRO_PUMP,"tm"),
//                        new MoveLearnSetEntry(Move.ICE_BEAM,"tm"),
//                        new MoveLearnSetEntry(Move.ICE_SPINNER,"tm"),
//                        new MoveLearnSetEntry(Move.ICICLE_SPEAR,"tm"),
//                        new MoveLearnSetEntry(Move.ICY_WIND,"tm"),
//                        new MoveLearnSetEntry(Move.IRON_DEFENSE,"tm"),
//                        new MoveLearnSetEntry(Move.LIQUIDATION,"tm"),
//                        new MoveLearnSetEntry(Move.MUD_SHOT,"tm"),
//                        new MoveLearnSetEntry(Move.NATURAL_GIFT,"tm"),
//                        new MoveLearnSetEntry(Move.PAYBACK,"tm"),
//                        new MoveLearnSetEntry(Move.PROTECT,"tm"),
//                        new MoveLearnSetEntry(Move.RAIN_DANCE,"tm"),
//                        new MoveLearnSetEntry(Move.RAZOR_SHELL,"tm"),
//                        new MoveLearnSetEntry(Move.REST,"tm"),
//                        new MoveLearnSetEntry(Move.RETURN,"tm"),
//                        new MoveLearnSetEntry(Move.ROCK_BLAST,"tm"),
//                        new MoveLearnSetEntry(Move.ROUND,"tm"),
//                        new MoveLearnSetEntry(Move.SCREECH,"tm"),
//                        new MoveLearnSetEntry(Move.SECRET_POWER,"tm"),
//                        new MoveLearnSetEntry(Move.SELFDESTRUCT,"tm"),
//                        new MoveLearnSetEntry(Move.SLEEP_TALK,"tm"),
//                        new MoveLearnSetEntry(Move.SNORE,"tm"),
//                        new MoveLearnSetEntry(Move.SNOWSCAPE,"tm"),
//                        new MoveLearnSetEntry(Move.SPIKES,"tm"),
//                        new MoveLearnSetEntry(Move.SUBSTITUTE,"tm"),
//                        new MoveLearnSetEntry(Move.SURF,"tm"),
//                        new MoveLearnSetEntry(Move.SWAGGER,"tm"),
//                        new MoveLearnSetEntry(Move.SWIFT,"tm"),
//                        new MoveLearnSetEntry(Move.TAKE_DOWN,"tm"),
//                        new MoveLearnSetEntry(Move.TERA_BLAST,"tm"),
//                        new MoveLearnSetEntry(Move.TOXIC,"tm"),
//                        new MoveLearnSetEntry(Move.TOXIC_SPIKES,"tm"),
//                        new MoveLearnSetEntry(Move.TRI_ATTACK,"tm"),
//                        new MoveLearnSetEntry(Move.WATERFALL,"tm"),
//                        new MoveLearnSetEntry(Move.WATER_PULSE,"tm"),
//                        new MoveLearnSetEntry(Move.WHIRLPOOL,"tm"),
//                        new MoveLearnSetEntry(Move.ATTRACT,"tutor"),
//                        new MoveLearnSetEntry(Move.AURORA_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.BARRIER,"tutor"),
//                        new MoveLearnSetEntry(Move.BIDE,"tutor"),
//                        new MoveLearnSetEntry(Move.BLIZZARD,"tutor"),
//                        new MoveLearnSetEntry(Move.BUBBLE_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.CLAMP,"tutor"),
//                        new MoveLearnSetEntry(Move.CURSE,"tutor"),
//                        new MoveLearnSetEntry(Move.DIVE,"tutor"),
//                        new MoveLearnSetEntry(Move.DOUBLEEDGE,"tutor"),
//                        new MoveLearnSetEntry(Move.DOUBLE_TEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.ENDURE,"tutor"),
//                        new MoveLearnSetEntry(Move.EXPLOSION,"tutor"),
//                        new MoveLearnSetEntry(Move.FACADE,"tutor"),
//                        new MoveLearnSetEntry(Move.FRUSTRATION,"tutor"),
//                        new MoveLearnSetEntry(Move.HEADBUTT,"tutor"),
//                        new MoveLearnSetEntry(Move.HIDDEN_POWER,"tutor"),
//                        new MoveLearnSetEntry(Move.HYDRO_PUMP,"tutor"),
//                        new MoveLearnSetEntry(Move.ICE_BEAM,"tutor"),
//                        new MoveLearnSetEntry(Move.ICE_SHARD,"tutor"),
//                        new MoveLearnSetEntry(Move.ICICLE_SPEAR,"tutor"),
//                        new MoveLearnSetEntry(Move.ICY_WIND,"tutor"),
//                        new MoveLearnSetEntry(Move.IRON_DEFENSE,"tutor"),
//                        new MoveLearnSetEntry(Move.LEER,"tutor"),
//                        new MoveLearnSetEntry(Move.LIQUIDATION,"tutor"),
//                        new MoveLearnSetEntry(Move.MIMIC,"tutor"),
//                        new MoveLearnSetEntry(Move.PROTECT,"tutor"),
//                        new MoveLearnSetEntry(Move.RAGE,"tutor"),
//                        new MoveLearnSetEntry(Move.RAIN_DANCE,"tutor"),
//                        new MoveLearnSetEntry(Move.RAPID_SPIN,"tutor"),
//                        new MoveLearnSetEntry(Move.REFLECT,"tutor"),
//                        new MoveLearnSetEntry(Move.REFRESH,"tutor"),
//                        new MoveLearnSetEntry(Move.REST,"tutor"),
//                        new MoveLearnSetEntry(Move.RETURN,"tutor"),
//                        new MoveLearnSetEntry(Move.SCREECH,"tutor"),
//                        new MoveLearnSetEntry(Move.SELFDESTRUCT,"tutor"),
//                        new MoveLearnSetEntry(Move.SHELL_SMASH,"tutor"),
//                        new MoveLearnSetEntry(Move.SLEEP_TALK,"tutor"),
//                        new MoveLearnSetEntry(Move.SNORE,"tutor"),
//                        new MoveLearnSetEntry(Move.SUBSTITUTE,"tutor"),
//                        new MoveLearnSetEntry(Move.SUPERSONIC,"tutor"),
//                        new MoveLearnSetEntry(Move.SURF,"tutor"),
//                        new MoveLearnSetEntry(Move.SWAGGER,"tutor"),
//                        new MoveLearnSetEntry(Move.SWIFT,"tutor"),
//                        new MoveLearnSetEntry(Move.TACKLE,"tutor"),
//                        new MoveLearnSetEntry(Move.TAKE_DOWN,"tutor"),
//                        new MoveLearnSetEntry(Move.TELEPORT,"tutor"),
//                        new MoveLearnSetEntry(Move.TOXIC,"tutor"),
//                        new MoveLearnSetEntry(Move.TRI_ATTACK,"tutor"),
//                        new MoveLearnSetEntry(Move.WATER_GUN,"tutor"),
//                        new MoveLearnSetEntry(Move.WATER_PULSE,"tutor"),
//                        new MoveLearnSetEntry(Move.WHIRLPOOL,"tutor"),
//                        new MoveLearnSetEntry(Move.WITHDRAW,"tutor"),
//                        new MoveLearnSetEntry(Move.VINE_WHIP,"tutor"),
//                        new MoveLearnSetEntry(Move.WORRY_SEED,"tutor")
//                        ),
//                List.of(Label.GEN1),
//                0, List.of(),
//                SpawnContext.SEAFLOOR, SpawnPool.COMMON, 12, 30, 9.9, List.of(
//                        new BiomeSpawnCondition(List.of(Biome.IS_OCEAN)),
//                        new SpawnCondition(SpawnConditionType.CANSEESKY,"true")
//                ), List.of(),
//                List.of(SpawnPreset.UNDERWATER),
//                0.8, 0.3,
//                List.of());
//        this.setCanSwim(false);
//        this.setIsNew(false);
//        this.setCanBreathUnderwater(true);
//        this.setSwimSpeed(0.1);
//        this.setHitbox(0.6,0.5);
//        this.setPortraitXYZ(0,1.8,0);
//    }
//}
