package drai.dev.gravelmon.games.pokemmo.secondbatch;

import drai.dev.gravelmon.pokemon.panjaea.*;

public class Panjaea extends drai.dev.gravelmon.games.registry.Game {
    public Panjaea() {
        super("Panjaea");
    }

    @Override
    public void registerPokemon() {
//        pokemon.add(new Owleaf());   Missing Stats
//        pokemon.add(new Fowliage());   Missing Stats
//        pokemon.add(new Strigallant());   Missing Stats
//        pokemon.add(new Coalverine());   Missing Stats
//        pokemon.add(new Charmaul());   Missing Stats
//        pokemon.add(new Brimscorch());   Missing Stats
//        pokemon.add(new Raindolph());   Missing Stats
//        pokemon.add(new Elkreek());   Missing Stats
//        pokemon.add(new Moocean());   Missing Stats
//        pokemon.add(new Caterpolar());   Missing Stats
//        pokemon.add(new Cryosalis());   Missing Stats
//        pokemon.add(new Monarctic());   Missing Stats
//        pokemon.add(new Leetle());   Missing Stats
//        pokemon.add(new Cherupace());   Missing Stats
//        pokemon.add(new Larviathan());   Missing Stats
//        pokemon.add(new Sassquish());   Missing Stats
//        pokemon.add(new 341676());   Missing Art
//        pokemon.add(new Malacute());   Missing Stats
//        pokemon.add(new Huskules());   Missing Stats
//        pokemon.add(new Turfin());   Missing Stats
//        pokemon.add(new Metalodon());   Missing Stats
//        pokemon.add(new Frostkey());   Missing Stats
//        pokemon.add(new Frostrike());   Missing Stats
//        pokemon.add(new Smallet());   Missing Stats
//        pokemon.add(new Stormmer());   Missing Stats
//        pokemon.add(new Kikkyu());   Missing Stats
        pokemon.add(new Necreon());
//        pokemon.add(new Tauroot());   Missing Stats
//        pokemon.add(new Taurmor());   Missing Stats
//        pokemon.add(new Minothorn());   Missing Stats
//        pokemon.add(new Cinduck());   Missing Stats
//        pokemon.add(new Volswan());   Missing Stats
//        pokemon.add(new Swanix());   Missing Stats
//        pokemon.add(new Minkler());   Missing Stats
//        pokemon.add(new Lagoonorak());   Missing Stats
//        pokemon.add(new Tsunamink());   Missing Stats
//        pokemon.add(new Rugrant());   Missing Stats
//        pokemon.add(new Perdizzy());   Missing Stats
//        pokemon.add(new Perdazzle());   Missing Stats
//        pokemon.add(new Pheaseance());   Missing Stats
//        pokemon.add(new Knoknok());   Missing Stats
//        pokemon.add(new Gravyle());   Missing Stats
//        pokemon.add(new Hardgoyle());   Missing Stats
//        pokemon.add(new Koolbeens());   Missing Stats
//        pokemon.add(new Straken());   Missing Stats
//        pokemon.add(new Adoraphin());   Missing Stats
//        pokemon.add(new Dolphet());   Missing Stats
//        pokemon.add(new Draphin());   Missing Stats
//        pokemon.add(new Elekina());   Missing Stats
//        pokemon.add(new Chargehog());   Missing Stats
//        pokemon.add(new Mosquick());   Missing Stats
//        pokemon.add(new Mosquiteer());   Missing Stats
//        pokemon.add(new Jetkundo());   Missing Stats
//        pokemon.add(new Purty());   Missing Stats
//        pokemon.add(new Luvly());   Missing Stats
//        pokemon.add(new Awfoal());   Missing Stats
//        pokemon.add(new Mulevolent());   Missing Stats
//        pokemon.add(new Voltergeist());   Missing Stats
//        pokemon.add(new Cardinoir());   Missing Stats
//        pokemon.add(new Cardinuit());   Missing Stats
//        pokemon.add(new Ramster());   Missing Stats
        pokemon.add(new Bladeon());
//        pokemon.add(new Bumblebaa());   Missing Stats
//        pokemon.add(new Womball());   Missing Stats
//        pokemon.add(new Wombatant());   Missing Stats
//        pokemon.add(new Cascavalve());   Missing Stats
//        pokemon.add(new Nozzleisk());   Missing Stats
//        pokemon.add(new Mossybara());   Missing Stats
//        pokemon.add(new Herbybara());   Missing Stats
//        pokemon.add(new Tropybara());   Missing Stats
//        pokemon.add(new Vulkit());   Missing Stats
//        pokemon.add(new Infeline());   Missing Stats
//        pokemon.add(new Jawar());   Missing Stats
//        pokemon.add(new Foamingo());   Missing Stats
//        pokemon.add(new Flowmingo());   Missing Stats
//        pokemon.add(new Fauxmingo());   Missing Stats
//        pokemon.add(new Gleech());   Missing Stats
//        pokemon.add(new Sparkeet());   Missing Stats
//        pokemon.add(new Shockatiel());   Missing Stats
//        pokemon.add(new Shockatoo());   Missing Stats
//        pokemon.add(new Rubbite());   Missing Stats
//        pokemon.add(new Trasharp());   Missing Stats
//        pokemon.add(new Leappa());   Missing Stats
//        pokemon.add(new Locrush());   Missing Stats
//        pokemon.add(new Sylphemy());   Missing Stats
//        pokemon.add(new Dankton());   Missing Stats
//        pokemon.add(new Planktarges());   Missing Stats
//        pokemon.add(new Toxow());   Missing Stats
//        pokemon.add(new Toxwine());   Missing Stats
//        pokemon.add(new Amallama());   Missing Stats
//        pokemon.add(new Llamagma());   Missing Stats
//        pokemon.add(new Cryoman());   Missing Stats
//        pokemon.add(new Stalagator());   Missing Stats
//        pokemon.add(new Pixiego());   Missing Stats
//        pokemon.add(new Faeroll());   Missing Stats
//        pokemon.add(new Fungoon());   Missing Stats
//        pokemon.add(new Truffian());   Missing Stats
//        pokemon.add(new Banditake());   Missing Stats
//        pokemon.add(new Auriconda());   Missing Stats
//        pokemon.add(new Octusy());   Missing Stats
//        pokemon.add(new Owleaf());   Missing Stats
//        pokemon.add(new Fowliage());   Missing Stats
//        pokemon.add(new Strigallant());   Missing Stats
//        pokemon.add(new Coalverine());   Missing Stats
//        pokemon.add(new Charmaul());   Missing Stats
//        pokemon.add(new Brimscorch());   Missing Stats
//        pokemon.add(new Raindolph());   Missing Stats
//        pokemon.add(new Elkreek());   Missing Stats
//        pokemon.add(new Moocean());   Missing Stats
//        pokemon.add(new Caterpolar());   Missing Stats
//        pokemon.add(new Cryosalis());   Missing Stats
//        pokemon.add(new Monarctic());   Missing Stats
//        pokemon.add(new Leetle());   Missing Stats
//        pokemon.add(new Cherupace());   Missing Stats
//        pokemon.add(new Larviathan());   Missing Stats
//        pokemon.add(new Sassquish());   Missing Stats
//        pokemon.add(new 341676());   Missing Art
//        pokemon.add(new Malacute());   Missing Stats
//        pokemon.add(new Huskules());   Missing Stats
//        pokemon.add(new Turfin());   Missing Stats
//        pokemon.add(new Metalodon());   Missing Stats
//        pokemon.add(new Frostkey());   Missing Stats
//        pokemon.add(new Frostrike());   Missing Stats
//        pokemon.add(new Smallet());   Missing Stats
//        pokemon.add(new Stormmer());   Missing Stats
//        pokemon.add(new Kikkyu());   Missing Stats
        pokemon.add(new Necreon());
//        pokemon.add(new Tauroot());   Missing Stats
//        pokemon.add(new Taurmor());   Missing Stats
//        pokemon.add(new Minothorn());   Missing Stats
//        pokemon.add(new Cinduck());   Missing Stats
//        pokemon.add(new Volswan());   Missing Stats
//        pokemon.add(new Swanix());   Missing Stats
//        pokemon.add(new Minkler());   Missing Stats
//        pokemon.add(new Lagoonorak());   Missing Stats
//        pokemon.add(new Tsunamink());   Missing Stats
//        pokemon.add(new Rugrant());   Missing Stats
//        pokemon.add(new Perdizzy());   Missing Stats
//        pokemon.add(new Perdazzle());   Missing Stats
//        pokemon.add(new Pheaseance());   Missing Stats
//        pokemon.add(new Knoknok());   Missing Stats
//        pokemon.add(new Gravyle());   Missing Stats
//        pokemon.add(new Hardgoyle());   Missing Stats
//        pokemon.add(new Koolbeens());   Missing Stats
//        pokemon.add(new Straken());   Missing Stats
//        pokemon.add(new Adoraphin());   Missing Stats
//        pokemon.add(new Dolphet());   Missing Stats
//        pokemon.add(new Draphin());   Missing Stats
//        pokemon.add(new Elekina());   Missing Stats
//        pokemon.add(new Chargehog());   Missing Stats
//        pokemon.add(new Mosquick());   Missing Stats
//        pokemon.add(new Mosquiteer());   Missing Stats
//        pokemon.add(new Jetkundo());   Missing Stats
//        pokemon.add(new Purty());   Missing Stats
//        pokemon.add(new Luvly());   Missing Stats
//        pokemon.add(new Awfoal());   Missing Stats
//        pokemon.add(new Mulevolent());   Missing Stats
//        pokemon.add(new Voltergeist());   Missing Stats
//        pokemon.add(new Cardinoir());   Missing Stats
//        pokemon.add(new Cardinuit());   Missing Stats
//        pokemon.add(new Ramster());   Missing Stats
        pokemon.add(new Bladeon());
//        pokemon.add(new Bumblebaa());   Missing Stats
//        pokemon.add(new Womball());   Missing Stats
//        pokemon.add(new Wombatant());   Missing Stats
//        pokemon.add(new Cascavalve());   Missing Stats
//        pokemon.add(new Nozzleisk());   Missing Stats
//        pokemon.add(new Mossybara());   Missing Stats
//        pokemon.add(new Herbybara());   Missing Stats
//        pokemon.add(new Tropybara());   Missing Stats
//        pokemon.add(new Vulkit());   Missing Stats
//        pokemon.add(new Infeline());   Missing Stats
//        pokemon.add(new Jawar());   Missing Stats
//        pokemon.add(new Foamingo());   Missing Stats
//        pokemon.add(new Flowmingo());   Missing Stats
//        pokemon.add(new Fauxmingo());   Missing Stats
//        pokemon.add(new Gleech());   Missing Stats
//        pokemon.add(new Sparkeet());   Missing Stats
//        pokemon.add(new Shockatiel());   Missing Stats
//        pokemon.add(new Shockatoo());   Missing Stats
//        pokemon.add(new Rubbite());   Missing Stats
//        pokemon.add(new Trasharp());   Missing Stats
//        pokemon.add(new Leappa());   Missing Stats
//        pokemon.add(new Locrush());   Missing Stats
//        pokemon.add(new Sylphemy());   Missing Stats
//        pokemon.add(new Dankton());   Missing Stats
//        pokemon.add(new Planktarges());   Missing Stats
//        pokemon.add(new Toxow());   Missing Stats
//        pokemon.add(new Toxwine());   Missing Stats
//        pokemon.add(new Amallama());   Missing Stats
//        pokemon.add(new Llamagma());   Missing Stats
//        pokemon.add(new Cryoman());   Missing Stats
//        pokemon.add(new Stalagator());   Missing Stats
//        pokemon.add(new Pixiego());   Missing Stats
//        pokemon.add(new Faeroll());   Missing Stats
//        pokemon.add(new Fungoon());   Missing Stats
//        pokemon.add(new Truffian());   Missing Stats
//        pokemon.add(new Banditake());   Missing Stats
//        pokemon.add(new Auriconda());   Missing Stats
    }

}
