package drai.dev.gravelmon.games;

import drai.dev.gravelmon.games.registry.*;
import drai.dev.gravelmon.pokemon.umbra.*;

public class Umbra extends Game {
    public Umbra() {        super("Umbra");    }

    @Override
    public void registerPokemon() {
        //TODO STARTER SET
        pokemon.add(new Psypole());
        pokemon.add(new Telefrog());
        pokemon.add(new Tarotoad());
        pokemon.add(new Boxeroo());
        pokemon.add(new Marsupunch());
        pokemon.add(new Kankombat());
        pokemon.add(new Seijitsu());
        pokemon.add(new Kousetsu());
        pokemon.add(new Mangetsu());
        pokemon.add(new Rockroach());
        pokemon.add(new Boulderoach());
        pokemon.add(new Axolil());
        pokemon.add(new Visimander());
        pokemon.add(new Webbat());
        pokemon.add(new Vamprachne());
        pokemon.add(new Cutesnoot());
        pokemon.add(new Coatisnotti());
        pokemon.add(new Ospuny());
        pokemon.add(new Osprowl());
        pokemon.add(new Ospredator());
        pokemon.add(new Pakrat());
        pokemon.add(new Bakpakrat());
        pokemon.add(new Royalarva());
        pokemon.add(new Superbpa());
        pokemon.add(new Regalocera());
        pokemon.add(new Carapad());
        pokemon.add(new Puripad());
        pokemon.add(new Simpaima());
        pokemon.add(new Arowisen());
        pokemon.add(new Spidoux());
        pokemon.add(new Aracide());
        pokemon.add(new Mimectar());
        pokemon.add(new Skittail());
        pokemon.add(new Timiphid());
        pokemon.add(new Chromite());
                                        //        pokemon.add(new Buzzybody()); NOT FINISHED
        pokemon.add(new Oviseed());
        pokemon.add(new Hoofern());
        pokemon.add(new Asparies());
        pokemon.add(new Pixipetal());
        pokemon.add(new Florafay());
        pokemon.add(new Zapouch());
        pokemon.add(new Mannovolt());
        pokemon.add(new Hemocto());
        pokemon.add(new Alucuttle());
        pokemon.add(new Sorroul());
        pokemon.add(new Depressoul());
        pokemon.add(new Spectorment());
        pokemon.add(new Accerval());
        pokemon.add(new Warrush());
        pokemon.add(new Hauntodile());
        pokemon.add(new Necrodile());
                                        //        pokemon.add(new Fashionistail()); NOT FINISHED
        pokemon.add(new Gichet());
        pokemon.add(new Crickjaw());
        pokemon.add(new Tascorch());
        pokemon.add(new Tastorture());
        pokemon.add(new Shrimpink());
        pokemon.add(new Armaroma());
        pokemon.add(new Pricklebun());
        pokemon.add(new Cackrabbit());
        pokemon.add(new Sonoralope());
        pokemon.add(new Chubren());
        pokemon.add(new Roadren());
        pokemon.add(new Malleamole());
        pokemon.add(new Shoxin());
        pokemon.add(new Noxurge());
        /*pokemon.add(new Bocolt());
        pokemon.add(new Chemara());
        pokemon.add(new Galliope());
        pokemon.add(new Curicoin());
        pokemon.add(new Paradime());
        pokemon.add(new Kikkop());
        pokemon.add(new Nyepeck());
        pokemon.add(new Nohbody());
        pokemon.add(new Meltose());
        pokemon.add(new Sugorch());
        pokemon.add(new Sadove());
        pokemon.add(new Charrion());
        pokemon.add(new Portile());
        pokemon.add(new Warptile());
        pokemon.add(new Hoplynx());
        pokemon.add(new Impalynx());
        pokemon.add(new Matchbux());
        pokemon.add(new Tinderbux());
        pokemon.add(new Agnibux());
        pokemon.add(new Buwayelo());
        pokemon.add(new Crocemor());
        pokemon.add(new Jericore());
        pokemon.add(new Exsnailibur());
        pokemon.add(new Windory());
        pokemon.add(new Kitesoon());
        pokemon.add(new Serrock());
        pokemon.add(new Kaijolt());
        pokemon.add(new Clayto());
        pokemon.add(new Paunchito());
        pokemon.add(new Starpent());
        pokemon.add(new Celestail());
        pokemon.add(new Smaquus());
        pokemon.add(new Hevolog());*/
        pokemon.add(new Calientoad());
        pokemon.add(new Picantoad());
        pokemon.add(new Volcantoad());
        /*pokemon.add(new Owlchemy());
        pokemon.add(new Knowitowl());
        pokemon.add(new Philosophowl());
        pokemon.add(new Purriah());
        pokemon.add(new Purradox());
        pokemon.add(new Oridjinn());
        pokemon.add(new Bubblisk());
        pokemon.add(new Gyezard());
        pokemon.add(new Pequeen());
        pokemon.add(new Cygnopera());
        pokemon.add(new Catopy());
        pokemon.add(new Flyberian());
        pokemon.add(new Pawthra());
        pokemon.add(new Bumblebear());
        pokemon.add(new Grizzlebee());
        pokemon.add(new Nestlap());
        pokemon.add(new Whamingo());
        pokemon.add(new Jerbola());
        pokemon.add(new Porculus());
        pokemon.add(new Lemohm());
        pokemon.add(new Circuitrus());
        pokemon.add(new Elecko());
        pokemon.add(new Caudalight());
        pokemon.add(new Jungfish());
        pokemon.add(new Osmophish());*/
        pokemon.add(new Baquini());
        pokemon.add(new Modelfin());
        pokemon.add(new Muertapoise());
        /*pokemon.add(new Kiddanuk());
        pokemon.add(new Charlechain());
        pokemon.add(new Dwarep());
        pokemon.add(new Antheratops());
        pokemon.add(new Polarep());
        pokemon.add(new Pelneo());
        pokemon.add(new Matrisite());
        pokemon.add(new Voltaig());
        pokemon.add(new Cnidrain());
        pokemon.add(new Plasmaw());
        pokemon.add(new Marmorest());
        pokemon.add(new Monkheat());
        pokemon.add(new Morozkong());
        pokemon.add(new Grace-H());
        pokemon.add(new Grace-I());
        pokemon.add(new Scion-V());
        pokemon.add(new Enderkoppen());
        pokemon.add(new Apochlys());*/

    }
}
